version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:cached
      - ~/.gitconfig:/root/.gitconfig:cached
      - ~/.wakatime.cfg:/root/.wakatime.cfg:cached
      - ~/.cache:/root/.cache:cached
      - ~/Github/bioin-401-project/data:/data:cached
    network_mode: service:neo4j
    command: sleep infinity

  neo4j:
    image: neo4j:5.16.0
    restart: unless-stopped
    volumes:
      - ~/Github/bioin-401-project/data/neo4j:/data:cached
    ports:
      - "7474:7474"
      - "7687:7687"
