version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LLAMA_INDEX_CACHE_DIR=/root/.cache
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 2gb
    volumes:
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:cached
      - ~/.gitconfig:/root/.gitconfig:cached
      - ~/.wakatime.cfg:/root/.wakatime.cfg:cached
      - ~/.cache:/root/.cache:cached
      - ~/Github/bioin-401-project/data:/data:cached
    command: sleep infinity

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - LLAMA_INDEX_CACHE_DIR=/root/.cache
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 2gb
    ports:
      - 8000:8000
    volumes:
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.cache:/root/.cache:cached
      - ~/Github/bioin-401-project/data:/data:cached
    working_dir: /workspaces/rgd-chatbot
    command: chainlit run -hw src/app.py


  nginx-proxy-manager:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ~/Github/bioin-401-project/data/nginx-proxy-manager/data:/data
      - ~/Github/bioin-401-project/data/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

  neo4j:
    image: neo4j:5.16.0
    restart: unless-stopped
    volumes:
      - ~/Github/bioin-401-project/data/neo4j:/data:cached
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]

  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest

volumes:
  ollama:
